hpi-schul-cloud/infra-deploy

.github/workflows/nextcloud-branch-deletion.yml, .github/workflows/nextcloud-deletion.yml, ansible/delete-bucket-playbook.yml, ansible/delete-namespace-playbook.yml
=> Ops 3853 fix

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml, ansible/group_vars/edusharing.yml
=> OPS-4091-rollout-edusharing

.github/workflows/edu-deploy-crawler.yml, .github/workflows/nextcloud-deletion.yml, .github/workflows/nextcloud-deploy.yml, ansible/templates/nextcloud_config_values
https://ticketsystem.dbildungscloud.de/browse/OPS-3681
=> OPS-3681-path-fix

ansible/templates/nextcloud_config_values
This configuration change should hide the logout button.
https://ticketsystem.dbildungscloud.de/browse/N21-594
=> N21-594 Hide logout button

ansible/group_vars/all.yml
=> N21-617 changed thr logo

ansible/group_vars/all.yml
=> N21-617 brb change icon

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml, ansible/group_vars/edusharing.yml
https://ticketsystem.dbildungscloud.de/browse/OPS-4417
=> OPS-4417-adjust-edusharing-users

ansible/group_vars/all.yml
Use the new user_oidcs version instead of the own release build.
https://ticketsystem.dbildungscloud.de/browse/N21-755
https://github.com/hpi-schul-cloud/schulcloud-nextcloud/pull/27
=> N21-755 use new user_oidc version

ansible/group_vars/all.yml
Fixes failure when env EXTERNAL_ARCHIVE_PLUGINS is missing.
=> N21-755 use new user OIDC version

.github/workflows/edu-dev-crawler.yml, .github/workflows/edu-s3-content-update.yml, .github/workflows/edu-s3-trigger-cronjob.yml, .github/workflows/nextcloud-branch-deletion.yml, README.md, ansible/group_vars/edusharing.yml, ansible/group_vars/prod.yml, ansible/group_vars/staging.yml, hosts
https://ticketsystem.dbildungscloud.de/browse/OPS-4165
=> OPS-4165-separate-bucket-credentials-per-stage

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml, ansible/group_vars/edusharing.yml
Enables the h5p crawler.
Ticket:
https://ticketsystem.dbildungscloud.de/browse/BRB-253 
Epic:
https://ticketsystem.dbildungscloud.de/browse/BRB-38
Add h5p-crawler to helmchart.
=> BRB-253-enable h5p crawler

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml
update the default version of the edusharing crawlers
https://ticketsystem.dbildungscloud.de/browse/OPS-4704
=> OPS-4704-update-crawler-staging-prod

hosts
=> OPS-4925 Added infra-dev-edusharing-01

ansible/edusharing-setup-playbook.yml, ansible/group_vars/edusharing.yml
https://ticketsystem.dbildungscloud.de/browse/OPS-4386
=> OPS-4386-recreate-edusharing-cluster

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml
=> OPS-5007-update-crawler-removal-rpi-content

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml, .github/workflows/edu-s3-content-update.yml, ansible/group_vars/edusharing.yml
Update Image version and add envs to permissions updater to fix settings of permissions
=> OPS-5039-update-permission-crawler

.github/workflows/edu-s3-content-update.yml
Update Kubernetes Version to 1.24.16 (used for installing kubectl)
=> OPS-5002-update-kubernetes-1.24

.github/workflows/edu-s3-content-update.yml
=> OPS-5045 Update Kubernetes to 1.25

ansible/group_vars/edusharing.yml
setup sctipt image version is old. Updated the version
=> OPS-5097-increase-edusharing-setup-image-version

ansible/edusharing-crawler-playbook.yml, ansible/edusharing-setup-playbook.yml, ansible/group_vars/edusharing.yml, ansible/host_vars/infra-dev-edusharing-1.yml, ansible/host_vars/infra-dev-edusharing-ops-5193.yaml, hosts
- make playbook more robust, especially when executed locally
- delete old infra-dev-edusahring-1 instance reference 
- decrease edusharing setup code tag to working version (working for also newly created instances)
=> OPS-5193-edusharing-kubernetes-update-1-26-improvements

.github/workflows/nextcloud-branch-deletion.yml, ansible/group_vars/all.yml
- limit that the secret reference only gets changed when to the sc-dev-nextcloud nbc-main namespace is pushed, so that development instance for the devs that have the type nbc are not affected. 
- also limit the deletion workflow so that it is not executed not only on nbc, but also on thr and brb
=> OPS-5486-fix-nextcloud-infra-deploy-rollouts

ansible/group_vars/all.yml, ansible/group_vars/dev.yml
=> OPS-5500-disable-collabora-nextcloud

ansible/group_vars/all.yml, ansible/group_vars/dev.yml
- update image verison 
- disable new plugin
=> OPS-5649-update-nextcloud

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml, ansible/edusharing-crawler-playbook.yml, ansible/group_vars/edusharing.yml
Fix for oeh crawler to oeh spider if the spider and the other crawlers work
- https://ticketsystem.dbildungscloud.de/browse/BC-8098
- https://ticketsystem.dbildungscloud.de/browse/DMED-119
=> BC-8098 - DMED-119 - fix oeh spider

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml
Like Thuringia, Lower Saxony has bought h5p content from the provider MedienLB. This content is to be made available to users via the learnstore NBC.
The H5P Edu-sharing Spider is written at python and reade an Excel file to get the Metadata set for an h5p content what is stored at an s3.
The Excel file has one line for each h5p content, this line has the Metadata and also the country for this file.
Bad ist if an H5P Content line is double with the same name and Metadata but the County is the same the H5P Spider would overwrite the old ones.
The reason for it is that the H5P Content aka File and Metadata in Both lines are mapped to the same hash at edu-sharing that result in best case in overwriting the old ones and at worst case the h5p spider crash and that it's.
To solve this the …
=> BC-8629 - Activate h5p-content “MedienLB” for NBC via Lernstore

.github/workflows/edu-crawler.yml, .github/workflows/edu-dev-crawler.yml, ansible/edusharing-crawler-playbook.yml, ansible/group_vars/edusharing.yml
JIRA :
- https://ticketsystem.dbildungscloud.de/browse/BC-9147
=> BC-9147 - Upgrade edu-sharing crawler from the original source
